language: python
python:
  - 3.7
  - 3.8
  - 3.9
before_install:
  - sudo rm -f /etc/boto.cfg  # https://github.com/travis-ci/travis-ci/issues/7940#issuecomment-310759657
install:
  - pip install coveralls tox-travis
script:
  - tox
after_success:
  - coveralls
